include:
  - CoreModules/CommonUI/spec.yml
  - CoreModules/Core/spec.yml
  - CoreModules/CoreUtils/spec.yml
  - SharedModules/BundleProvider/spec.yml
  - SharedModules/RxSwiftExtensions/spec.yml

name: App
options:
  postGenCommand: pod install
targets:
  App:
    dependencies:
      - target: Core
      - target: RxSwiftExtensions
      - target: CommonUI
      - target: BundleProvider
      - target: CoreUtils
    deploymentTarget: '13.0'
    platform: iOS
    postBuildScripts:
      - inputFiles:
          - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}
          - $(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)
        name: Crashlytics
        script: ${PODS_ROOT}/FirebaseCrashlytics/run
    settings:
      base:
        CODE_SIGN_STYLE: Automatic
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        DEVELOPMENT_TEAM: TFAR74HVP6
        INFOPLIST_FILE: App/Info.plist
        SWIFT_VERSION: 5
        TARGETED_DEVICE_FAMILY: 1
    sources:
      - path: App
    type: application